export interface CurrencyInfo {
  code: string;
  symbol: string;
  name: string;
  country: string;
}

export const CURRENCIES: CurrencyInfo[] = [
  { code: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham", country: "United Arab Emirates" },
  { code: "AFN", symbol: "؋", name: "Afghan Afghani", country: "Afghanistan" },
  { code: "ALL", symbol: "L", name: "Albanian Lek", country: "Albania" },
  { code: "AMD", symbol: "֏", name: "Armenian Dram", country: "Armenia" },
  { code: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder", country: "Curaçao, Sint Maarten" },
  { code: "AOA", symbol: "Kz", name: "Angolan Kwanza", country: "Angola" },
  { code: "ARS", symbol: "$", name: "Argentine Peso", country: "Argentina" },
  { code: "AUD", symbol: "A$", name: "Australian Dollar", country: "Australia" },
  { code: "AWG", symbol: "ƒ", name: "Aruban Florin", country: "Aruba" },
  { code: "AZN", symbol: "₼", name: "Azerbaijani Manat", country: "Azerbaijan" },
  { code: "BAM", symbol: "KM", name: "Bosnia and Herzegovina Convertible Mark", country: "Bosnia and Herzegovina" },
  { code: "BBD", symbol: "$", name: "Barbadian Dollar", country: "Barbados" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka", country: "Bangladesh" },
  { code: "BGN", symbol: "лв", name: "Bulgarian Lev", country: "Bulgaria" },
  { code: "BHD", symbol: "د.ب", name: "Bahraini Dinar", country: "Bahrain" },
  { code: "BIF", symbol: "FBu", name: "Burundian Franc", country: "Burundi" },
  { code: "BMD", symbol: "$", name: "Bermudian Dollar", country: "Bermuda" },
  { code: "BND", symbol: "$", name: "Brunei Dollar", country: "Brunei" },
  { code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano", country: "Bolivia" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real", country: "Brazil" },
  { code: "BSD", symbol: "$", name: "Bahamian Dollar", country: "Bahamas" },
  { code: "BWP", symbol: "P", name: "Botswana Pula", country: "Botswana" },
  { code: "BYN", symbol: "Br", name: "Belarusian Ruble", country: "Belarus" },
  { code: "BZD", symbol: "$", name: "Belize Dollar", country: "Belize" },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar", country: "Canada" },
  { code: "CDF", symbol: "FC", name: "Congolese Franc", country: "DR Congo" },
  { code: "CHF", symbol: "CHF", name: "Swiss Franc", country: "Switzerland" },
  { code: "CLP", symbol: "$", name: "Chilean Peso", country: "Chile" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan", country: "China" },
  { code: "COP", symbol: "$", name: "Colombian Peso", country: "Colombia" },
  { code: "CRC", symbol: "₡", name: "Costa Rican Colón", country: "Costa Rica" },
  { code: "CUP", symbol: "$", name: "Cuban Peso", country: "Cuba" },
  { code: "CVE", symbol: "$", name: "Cape Verdean Escudo", country: "Cape Verde" },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna", country: "Czech Republic" },
  { code: "DJF", symbol: "Fdj", name: "Djiboutian Franc", country: "Djibouti" },
  { code: "DKK", symbol: "kr", name: "Danish Krone", country: "Denmark" },
  { code: "DOP", symbol: "RD$", name: "Dominican Peso", country: "Dominican Republic" },
  { code: "DZD", symbol: "د.ج", name: "Algerian Dinar", country: "Algeria" },
  { code: "EGP", symbol: "E£", name: "Egyptian Pound", country: "Egypt" },
  { code: "ERN", symbol: "Nfk", name: "Eritrean Nakfa", country: "Eritrea" },
  { code: "ETB", symbol: "Br", name: "Ethiopian Birr", country: "Ethiopia" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Eurozone" },
  { code: "FJD", symbol: "$", name: "Fijian Dollar", country: "Fiji" },
  { code: "FKP", symbol: "£", name: "Falkland Islands Pound", country: "Falkland Islands" },
  { code: "GBP", symbol: "£", name: "British Pound", country: "United Kingdom" },
  { code: "GEL", symbol: "₾", name: "Georgian Lari", country: "Georgia" },
  { code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi", country: "Ghana" },
  { code: "GIP", symbol: "£", name: "Gibraltar Pound", country: "Gibraltar" },
  { code: "GMD", symbol: "D", name: "Gambian Dalasi", country: "Gambia" },
  { code: "GNF", symbol: "FG", name: "Guinean Franc", country: "Guinea" },
  { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal", country: "Guatemala" },
  { code: "GYD", symbol: "$", name: "Guyanese Dollar", country: "Guyana" },
  { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar", country: "Hong Kong" },
  { code: "HNL", symbol: "L", name: "Honduran Lempira", country: "Honduras" },
  { code: "HRK", symbol: "kn", name: "Croatian Kuna", country: "Croatia" },
  { code: "HTG", symbol: "G", name: "Haitian Gourde", country: "Haiti" },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint", country: "Hungary" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah", country: "Indonesia" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel", country: "Israel" },
  { code: "INR", symbol: "₹", name: "Indian Rupee", country: "India" },
  { code: "IQD", symbol: "ع.د", name: "Iraqi Dinar", country: "Iraq" },
  { code: "IRR", symbol: "﷼", name: "Iranian Rial", country: "Iran" },
  { code: "ISK", symbol: "kr", name: "Icelandic Króna", country: "Iceland" },
  { code: "JMD", symbol: "J$", name: "Jamaican Dollar", country: "Jamaica" },
  { code: "JOD", symbol: "د.ا", name: "Jordanian Dinar", country: "Jordan" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen", country: "Japan" },
  { code: "KES", symbol: "KSh", name: "Kenyan Shilling", country: "Kenya" },
  { code: "KGS", symbol: "сом", name: "Kyrgyzstani Som", country: "Kyrgyzstan" },
  { code: "KHR", symbol: "៛", name: "Cambodian Riel", country: "Cambodia" },
  { code: "KMF", symbol: "CF", name: "Comorian Franc", country: "Comoros" },
  { code: "KRW", symbol: "₩", name: "South Korean Won", country: "South Korea" },
  { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar", country: "Kuwait" },
  { code: "KYD", symbol: "$", name: "Cayman Islands Dollar", country: "Cayman Islands" },
  { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge", country: "Kazakhstan" },
  { code: "LAK", symbol: "₭", name: "Lao Kip", country: "Laos" },
  { code: "LBP", symbol: "L£", name: "Lebanese Pound", country: "Lebanon" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee", country: "Sri Lanka" },
  { code: "LRD", symbol: "$", name: "Liberian Dollar", country: "Liberia" },
  { code: "LSL", symbol: "L", name: "Lesotho Loti", country: "Lesotho" },
  { code: "LYD", symbol: "ل.د", name: "Libyan Dinar", country: "Libya" },
  { code: "MAD", symbol: "د.م.", name: "Moroccan Dirham", country: "Morocco" },
  { code: "MDL", symbol: "L", name: "Moldovan Leu", country: "Moldova" },
  { code: "MGA", symbol: "Ar", name: "Malagasy Ariary", country: "Madagascar" },
  { code: "MKD", symbol: "ден", name: "Macedonian Denar", country: "North Macedonia" },
  { code: "MMK", symbol: "K", name: "Myanmar Kyat", country: "Myanmar" },
  { code: "MNT", symbol: "₮", name: "Mongolian Tögrög", country: "Mongolia" },
  { code: "MOP", symbol: "MOP$", name: "Macanese Pataca", country: "Macao" },
  { code: "MRU", symbol: "UM", name: "Mauritanian Ouguiya", country: "Mauritania" },
  { code: "MUR", symbol: "₨", name: "Mauritian Rupee", country: "Mauritius" },
  { code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa", country: "Maldives" },
  { code: "MWK", symbol: "MK", name: "Malawian Kwacha", country: "Malawi" },
  { code: "MXN", symbol: "Mex$", name: "Mexican Peso", country: "Mexico" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit", country: "Malaysia" },
  { code: "MZN", symbol: "MT", name: "Mozambican Metical", country: "Mozambique" },
  { code: "NAD", symbol: "N$", name: "Namibian Dollar", country: "Namibia" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira", country: "Nigeria" },
  { code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba", country: "Nicaragua" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone", country: "Norway" },
  { code: "NPR", symbol: "रू", name: "Nepalese Rupee", country: "Nepal" },
  { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar", country: "New Zealand" },
  { code: "OMR", symbol: "﷼", name: "Omani Rial", country: "Oman" },
  { code: "PAB", symbol: "B/.", name: "Panamanian Balboa", country: "Panama" },
  { code: "PEN", symbol: "S/.", name: "Peruvian Sol", country: "Peru" },
  { code: "PGK", symbol: "K", name: "Papua New Guinean Kina", country: "Papua New Guinea" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso", country: "Philippines" },
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee", country: "Pakistan" },
  { code: "PLN", symbol: "zł", name: "Polish Złoty", country: "Poland" },
  { code: "PYG", symbol: "₲", name: "Paraguayan Guaraní", country: "Paraguay" },
  { code: "QAR", symbol: "﷼", name: "Qatari Riyal", country: "Qatar" },
  { code: "RON", symbol: "lei", name: "Romanian Leu", country: "Romania" },
  { code: "RSD", symbol: "дин.", name: "Serbian Dinar", country: "Serbia" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble", country: "Russia" },
  { code: "RWF", symbol: "FRw", name: "Rwandan Franc", country: "Rwanda" },
  { code: "SAR", symbol: "﷼", name: "Saudi Riyal", country: "Saudi Arabia" },
  { code: "SBD", symbol: "$", name: "Solomon Islands Dollar", country: "Solomon Islands" },
  { code: "SCR", symbol: "₨", name: "Seychellois Rupee", country: "Seychelles" },
  { code: "SDG", symbol: "ج.س.", name: "Sudanese Pound", country: "Sudan" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona", country: "Sweden" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar", country: "Singapore" },
  { code: "SHP", symbol: "£", name: "Saint Helena Pound", country: "Saint Helena" },
  { code: "SLE", symbol: "Le", name: "Sierra Leonean Leone", country: "Sierra Leone" },
  { code: "SOS", symbol: "Sh.So.", name: "Somali Shilling", country: "Somalia" },
  { code: "SRD", symbol: "$", name: "Surinamese Dollar", country: "Suriname" },
  { code: "SSP", symbol: "£", name: "South Sudanese Pound", country: "South Sudan" },
  { code: "STN", symbol: "Db", name: "São Tomé Dobra", country: "São Tomé and Príncipe" },
  { code: "SVC", symbol: "$", name: "Salvadoran Colón", country: "El Salvador" },
  { code: "SYP", symbol: "LS", name: "Syrian Pound", country: "Syria" },
  { code: "SZL", symbol: "E", name: "Eswatini Lilangeni", country: "Eswatini" },
  { code: "THB", symbol: "฿", name: "Thai Baht", country: "Thailand" },
  { code: "TJS", symbol: "ЅМ", name: "Tajikistani Somoni", country: "Tajikistan" },
  { code: "TMT", symbol: "T", name: "Turkmenistan Manat", country: "Turkmenistan" },
  { code: "TND", symbol: "د.ت", name: "Tunisian Dinar", country: "Tunisia" },
  { code: "TOP", symbol: "T$", name: "Tongan Paʻanga", country: "Tonga" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira", country: "Turkey" },
  { code: "TTD", symbol: "TT$", name: "Trinidad and Tobago Dollar", country: "Trinidad and Tobago" },
  { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar", country: "Taiwan" },
  { code: "TZS", symbol: "TSh", name: "Tanzanian Shilling", country: "Tanzania" },
  { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia", country: "Ukraine" },
  { code: "UGX", symbol: "USh", name: "Ugandan Shilling", country: "Uganda" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "United States" },
  { code: "UYU", symbol: "$U", name: "Uruguayan Peso", country: "Uruguay" },
  { code: "UZS", symbol: "soʻm", name: "Uzbekistani Som", country: "Uzbekistan" },
  { code: "VES", symbol: "Bs.S", name: "Venezuelan Bolívar", country: "Venezuela" },
  { code: "VND", symbol: "₫", name: "Vietnamese Đồng", country: "Vietnam" },
  { code: "VUV", symbol: "VT", name: "Vanuatu Vatu", country: "Vanuatu" },
  { code: "WST", symbol: "WS$", name: "Samoan Tālā", country: "Samoa" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc", country: "Central Africa" },
  { code: "XCD", symbol: "EC$", name: "East Caribbean Dollar", country: "East Caribbean" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc", country: "West Africa" },
  { code: "XPF", symbol: "CFP", name: "CFP Franc", country: "French Pacific" },
  { code: "YER", symbol: "﷼", name: "Yemeni Rial", country: "Yemen" },
  { code: "ZAR", symbol: "R", name: "South African Rand", country: "South Africa" },
  { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha", country: "Zambia" },
  { code: "ZWG", symbol: "ZiG", name: "Zimbabwe Gold", country: "Zimbabwe" }
].sort((a, b) => a.code.localeCompare(b.code));

export function getCurrencyByCode(code?: string): CurrencyInfo {
  if (!code) return CURRENCIES.find(c => c.code === "BDT") || CURRENCIES[0];
  const found = CURRENCIES.find(c => c.code.toUpperCase() === code.toUpperCase());
  return found || { code: code.toUpperCase(), symbol: "৳", name: code.toUpperCase(), country: "" };
}
