"use client";

import React, { useState, useTransition } from "react";
import { Search, FileDown, Printer, Clock, RefreshCw, Building2 } from "lucide-react";
import { Table, Thead, Tbody, Tfoot, Tr, Th, Td, EmptyState } from "@/templates/egg-tasta/components";
import { useCurrency } from "@/shared/components/regional-context";
import { getCustomerDueListAction } from "@/templates/egg-tasta/actions/customers";

export interface CustomerDueClientProps {
  initialData: any[];
  initialSummary: {
    totalCustomers: number;
    totalSales: number;
    totalCollection: number;
    totalOutstandingDue: number;
  };
  headerData?: {
    businessName: string;
    logoUrl?: string | null;
    address: string;
    phone: string;
    printedBy: string;
    generatedAt: string;
  };
}

export function CustomerDueClient({
  initialData,
  initialSummary,
  headerData = {
    businessName: "Egg Tasta ERP",
    logoUrl: null,
    address: "Main Outlet Road, Dhaka, Bangladesh",
    phone: "+880 1700-000000",
    printedBy: "Business Admin",
    generatedAt: new Date().toLocaleString(),
  },
}: CustomerDueClientProps) {
  const { formatCurrency } = useCurrency();
  const [isPending, startTransition] = useTransition();

  const [data, setData] = useState<any[]>(initialData);
  const [summary, setSummary] = useState(initialSummary);
  const [search, setSearch] = useState("");
  const [dueFilter, setDueFilter] = useState("ALL");

  function fetchDues(newSearch = search, newFilter = dueFilter) {
    startTransition(async () => {
      const res = await getCustomerDueListAction({
        search: newSearch,
        filter: newFilter,
      });

      if (res.success) {
        setData(res.data || []);
        if (res.summary) setSummary(res.summary);
      }
    });
  }

  function handlePrint() {
    window.print();
  }

  function exportCSV() {
    if (data.length === 0) return;

    const headers = [
      "SL#",
      "Customer Code",
      "Customer Name",
      "Phone",
      "Total Sales",
      "Total Collection",
      "Current Due",
      "Last Transaction Date",
    ];
    const rows = data.map((item, index) => [
      index + 1,
      item.customerCode || "",
      `"${(item.name || "").replace(/"/g, '""')}"`,
      `"${(item.phone || "").replace(/"/g, '""')}"`,
      `"${formatCurrency(item.totalSales || 0)}"`,
      `"${formatCurrency(item.totalCollection || 0)}"`,
      `"${formatCurrency(item.currentDue || 0)}"`,
      item.lastTransactionDate ? new Date(item.lastTransactionDate).toLocaleDateString() : "",
    ]);

    const totalRow = [
      "TOTAL",
      "TOTAL CUSTOMERS",
      `"Customers: ${summary.totalCustomers}"`,
      '""',
      `"${formatCurrency(summary.totalSales || 0)}"`,
      `"${formatCurrency(summary.totalCollection || 0)}"`,
      `"${formatCurrency(summary.totalOutstandingDue || 0)}"`,
      '""',
    ];

    const csvContent =
      "data:text/csv;charset=utf-8," +
      [headers.join(","), ...rows.map((e) => e.join(",")), totalRow.join(",")].join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Customer_Due_List_${new Date().toISOString().split("T")[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  return (
    <div className="space-y-6">
      {/* Global Print Styles for Accounting Software Report */}
      <style jsx global>{`
        @media print {
          @page {
            size: A4 portrait;
            margin: 10mm 10mm 15mm 10mm;
            @bottom-right {
              content: "Page " counter(page) " of " counter(pages);
              font-size: 8pt;
              font-family: var(--font-inter), sans-serif;
              color: #334155;
            }
            @bottom-left {
              content: "Generated by ERP Platform";
              font-size: 8pt;
              font-family: var(--font-inter), sans-serif;
              color: #334155;
            }
          }
          html, body {
            background: #ffffff !important;
            color: #000000 !important;
            font-family: var(--font-inter), 'Noto Sans Bengali', system-ui, sans-serif !important;
            font-size: 9pt !important;
            margin: 0 !important;
            padding: 0 !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .no-print, nav, header, sidebar, aside, button, select, input, .no-print * {
            display: none !important;
          }
          #due-list-print-section {
            display: block !important;
            width: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
          }
          table {
            width: 100% !important;
            border-collapse: collapse !important;
            margin-top: 8px !important;
          }
          thead {
            display: table-header-group !important;
          }
          tfoot {
            display: table-footer-group !important;
          }
          tr {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }
          th {
            background-color: #f1f5f9 !important;
            color: #000000 !important;
            border: 1px solid #475569 !important;
            padding: 5px 6px !important;
            font-weight: 700 !important;
            font-size: 8.5pt !important;
          }
          td {
            border: 1px solid #64748b !important;
            padding: 4px 6px !important;
            font-size: 8.5pt !important;
            color: #000000 !important;
            background: #ffffff !important;
          }
          tfoot td {
            background-color: #f1f5f9 !important;
            color: #000000 !important;
            font-weight: 700 !important;
            border-top: 2px solid #000000 !important;
          }
        }
      `}</style>

      {/* WEB UI ONLY - Top Cards */}
      <div className="no-print grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm">
          <div className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Total Customers
          </div>
          <div className="text-2xl font-bold mt-1 text-slate-900 dark:text-white">
            {summary.totalCustomers}
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm">
          <div className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Total Sales
          </div>
          <div className="text-2xl font-bold mt-1 text-slate-900 dark:text-white">
            {formatCurrency(summary.totalSales)}
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm">
          <div className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Total Collection
          </div>
          <div className="text-2xl font-bold mt-1 text-emerald-600 dark:text-emerald-400">
            {formatCurrency(summary.totalCollection)}
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm">
          <div className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Total Outstanding Due
          </div>
          <div className="text-2xl font-bold mt-1 text-rose-600 dark:text-rose-400">
            {formatCurrency(summary.totalOutstandingDue)}
          </div>
        </div>
      </div>

      {/* WEB UI ONLY - Top Bar Actions & Filters */}
      <div className="no-print bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4 shadow-sm flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
          <div className="relative w-full sm:w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
            <input
              type="text"
              placeholder="Search by code, name, phone..."
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                fetchDues(e.target.value, dueFilter);
              }}
              className="pl-9 pr-4 py-2 bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 w-full text-slate-900 dark:text-white"
            />
          </div>

          <select
            value={dueFilter}
            onChange={(e) => {
              setDueFilter(e.target.value);
              fetchDues(search, e.target.value);
            }}
            className="px-3 py-2 bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 w-full sm:w-auto text-slate-900 dark:text-white"
          >
            <option value="ALL">All Customers</option>
            <option value="DUE_ONLY">Outstanding Dues Only</option>
            <option value="ZERO">Zero / Clear Balance</option>
          </select>
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
          <button
            onClick={exportCSV}
            className="px-4 py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800 rounded-xl font-medium text-sm flex items-center gap-2 shadow-sm transition-colors"
          >
            <FileDown className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
            Export CSV
          </button>

          <button
            onClick={handlePrint}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-medium text-sm flex items-center gap-2 shadow-sm transition-colors"
          >
            <Printer className="h-4 w-4" />
            Print Report
          </button>
        </div>
      </div>

      {/* WEB UI - Interactive Table */}
      <div className="no-print bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl overflow-hidden shadow-sm">
        {isPending && (
          <div className="bg-blue-50/50 dark:bg-blue-900/20 px-4 py-2 text-xs text-blue-600 dark:text-blue-400 flex items-center gap-2">
            <RefreshCw className="h-3.5 w-3.5 animate-spin" />
            Updating due list...
          </div>
        )}

        {data.length === 0 ? (
          <EmptyState
            title="No Customers Found"
            description="No customer records match your filter parameters."
            icon={Clock}
          />
        ) : (
          <Table>
            <Thead>
              <Tr>
                <Th className="w-12 text-center">SL#</Th>
                <Th>Customer Code</Th>
                <Th>Customer Name</Th>
                <Th>Phone</Th>
                <Th className="text-right">Total Sales</Th>
                <Th className="text-right">Total Collection</Th>
                <Th className="text-right">Current Due</Th>
                <Th className="text-right">Last Transaction Date</Th>
              </Tr>
            </Thead>
            <Tbody>
              {data.map((c, index) => (
                <Tr key={c.id || index}>
                  <Td className="text-center font-mono text-xs text-slate-500">{index + 1}</Td>
                  <Td className="font-mono text-xs font-bold text-blue-600 dark:text-blue-400">
                    {c.customerCode}
                  </Td>
                  <Td className="font-medium text-slate-900 dark:text-slate-100">{c.name || "-"}</Td>
                  <Td className="text-slate-600 dark:text-slate-400">{c.phone || "-"}</Td>
                  <Td className="text-right font-medium">{formatCurrency(c.totalSales)}</Td>
                  <Td className="text-right font-medium text-emerald-600 dark:text-emerald-400">
                    {formatCurrency(c.totalCollection)}
                  </Td>
                  <Td className={`text-right font-bold ${c.currentDue > 0 ? "text-rose-600 dark:text-rose-400" : "text-slate-900 dark:text-white"}`}>
                    {formatCurrency(c.currentDue)}
                  </Td>
                  <Td className="text-right text-xs text-slate-500">
                    {c.lastTransactionDate ? new Date(c.lastTransactionDate).toLocaleDateString() : "-"}
                  </Td>
                </Tr>
              ))}
            </Tbody>
            <Tfoot>
              <Tr className="bg-slate-100/90 dark:bg-slate-800/80 font-bold border-t-2 border-slate-300 dark:border-slate-700">
                <Td className="font-bold uppercase tracking-wider text-slate-900 dark:text-white text-center">TOTAL</Td>
                <Td className="font-bold text-slate-900 dark:text-white" colSpan={2}>Customers: {summary.totalCustomers}</Td>
                <Td className="text-slate-500 dark:text-slate-400">-</Td>
                <Td className="text-right font-bold text-slate-900 dark:text-white">{formatCurrency(summary.totalSales)}</Td>
                <Td className="text-right font-bold text-emerald-600 dark:text-emerald-400">{formatCurrency(summary.totalCollection)}</Td>
                <Td className="text-right font-bold text-rose-600 dark:text-rose-400">{formatCurrency(summary.totalOutstandingDue)}</Td>
                <Td className="text-right text-slate-500 dark:text-slate-400">-</Td>
              </Tr>
            </Tfoot>
          </Table>
        )}
      </div>

      {/* DEDICATED PRINT-ONLY ACCOUNTING REPORT */}
      <div id="due-list-print-section" className="hidden print:block text-black bg-white">
        {/* Accounting Report Header */}
        <div className="border-b-2 border-slate-900 pb-3 mb-3 flex justify-between items-start">
          <div className="flex items-center gap-3">
            {headerData.logoUrl ? (
              <img src={headerData.logoUrl} alt="Business Logo" className="h-12 max-w-[120px] object-contain shrink-0" />
            ) : (
              <div className="h-10 w-10 bg-slate-900 text-white font-bold flex items-center justify-center text-lg rounded">
                <Building2 className="h-5 w-5" />
              </div>
            )}
            <div>
              <h1 className="text-lg font-bold uppercase tracking-wider text-slate-900 leading-tight">
                {headerData.businessName}
              </h1>
              <p className="text-[11px] text-slate-800 leading-tight">{headerData.address}</p>
              <p className="text-[11px] text-slate-800 leading-tight">Phone: {headerData.phone}</p>
            </div>
          </div>

          <div className="text-right">
            <h2 className="text-base font-bold text-slate-900 uppercase tracking-wide">
              CUSTOMER DUE LIST
            </h2>
            <p className="text-[11px] text-slate-800 mt-0.5">Printed: <strong>{headerData.generatedAt}</strong></p>
            <p className="text-[11px] text-slate-800">Printed By: <strong>{headerData.printedBy}</strong></p>
          </div>
        </div>

        {/* Report Filter Metadata Bar */}
        <div className="flex justify-between items-center text-[11px] text-slate-800 mb-3 px-2 py-1 bg-slate-100 border border-slate-400">
          <div>
            <strong>Report Filter:</strong> {dueFilter === "DUE_ONLY" ? "Outstanding Dues Only" : dueFilter === "ZERO" ? "Zero / Clear Balance Only" : "All Customers"}
            {search ? ` | Search Query: "${search}"` : ""}
          </div>
          <div>
            <strong>Total Customers:</strong> {summary.totalCustomers}
          </div>
        </div>

        {/* Accounting Grid Table (7 Columns: SL#, Customer Name, Phone, Total Sales, Total Collection, Current Due, Last Txn Date) */}
        <table className="w-full text-[11px] border-collapse border border-slate-900">
          <thead>
            <tr className="bg-slate-200 text-slate-900 border-b-2 border-slate-900">
              <th className="border border-slate-600 px-2 py-1.5 text-center font-bold w-10">SL#</th>
              <th className="border border-slate-600 px-2 py-1.5 text-left font-bold">Customer Name</th>
              <th className="border border-slate-600 px-2 py-1.5 text-left font-bold w-28">Phone</th>
              <th className="border border-slate-600 px-2 py-1.5 text-right font-bold w-28">Total Sales</th>
              <th className="border border-slate-600 px-2 py-1.5 text-right font-bold w-28">Total Collection</th>
              <th className="border border-slate-600 px-2 py-1.5 text-right font-bold w-28">Current Due</th>
              <th className="border border-slate-600 px-2 py-1.5 text-center font-bold w-24">Last Txn Date</th>
            </tr>
          </thead>
          <tbody>
            {data.map((c, index) => (
              <tr key={c.id || index} className="border-b border-slate-400">
                <td className="border border-slate-400 px-2 py-1 text-center font-mono">{index + 1}</td>
                <td className="border border-slate-400 px-2 py-1 font-bold text-slate-900">{c.name || "-"}</td>
                <td className="border border-slate-400 px-2 py-1 text-slate-900">{c.phone || "-"}</td>
                <td className="border border-slate-400 px-2 py-1 text-right font-mono">{formatCurrency(c.totalSales)}</td>
                <td className="border border-slate-400 px-2 py-1 text-right font-mono text-slate-900">{formatCurrency(c.totalCollection)}</td>
                <td className="border border-slate-400 px-2 py-1 text-right font-mono font-bold text-slate-900">{formatCurrency(c.currentDue)}</td>
                <td className="border border-slate-400 px-2 py-1 text-center text-slate-800 text-[10px]">
                  {c.lastTransactionDate ? new Date(c.lastTransactionDate).toLocaleDateString() : "-"}
                </td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr className="bg-slate-200 text-slate-900 font-bold border-t-2 border-slate-900">
              <td className="border border-slate-600 px-2 py-1.5 text-center uppercase font-bold">
                TOTAL
              </td>
              <td className="border border-slate-600 px-2 py-1.5 font-bold">
                TOTAL CUSTOMERS: {summary.totalCustomers}
              </td>
              <td className="border border-slate-600 px-2 py-1.5 text-center">-</td>
              <td className="border border-slate-600 px-2 py-1.5 text-right font-mono font-bold">
                {formatCurrency(summary.totalSales)}
              </td>
              <td className="border border-slate-600 px-2 py-1.5 text-right font-mono font-bold">
                {formatCurrency(summary.totalCollection)}
              </td>
              <td className="border border-slate-600 px-2 py-1.5 text-right font-mono font-bold text-slate-900">
                {formatCurrency(summary.totalOutstandingDue)}
              </td>
              <td className="border border-slate-600 px-2 py-1.5 text-center">-</td>
            </tr>
          </tfoot>
        </table>

        {/* Report Footer */}
        <div className="mt-4 pt-2 border-t border-slate-400 flex justify-between items-center text-[10px] text-slate-700">
          <div>Generated by ERP Platform</div>
          <div>Report: Customer Due List</div>
        </div>
      </div>
    </div>
  );
}


